version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing packages...
      - npm install
      - npm install -g nest
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'
